'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def even_Fibonacci_numbers(upper_limit):
    if (upper_limit < 1):
        return 0

    result = 0
    t1 = 0
    t2 = 1
    while True:
        t = t1 + t2
        if (t > upper_limit):
            break
        
        if (t % 2 == 0):
            result += t

        t1 = t2
        t2 = t

    return result

print(even_Fibonacci_numbers(4000000))